# netlify.toml
# This configuration correctly builds a monorepo with a separate backend and frontend.

# Main build settings, which will be executed from the project root.
[build]
  # 1. Install dependencies for the backend.
  # 2. Install dependencies for the frontend.
  # 3. Run the 'build' script inside the frontend folder.
  command = "npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend"
  
  # The directory containing your serverless functions, relative to the root.
  functions = "backend/functions"
  
  # The directory containing your built frontend site, relative to the root.
  publish = "frontend/build"

# Serverless Functions settings
[functions]
  # This is the key: it copies these files into the functions' deployment package
  # so your live server function can access them.
  included_files = ["backend/data.js", "backend/database.sqlite"]
