# netlify.toml

# Base settings for the build
[build]
  # This tells Netlify that all build-related commands and paths
  # should be run from inside the 'frontend' directory.
  base = "frontend"
  
  # This is the command Netlify will run to install dependencies and build your frontend.
  # It now runs inside the 'frontend' directory.
  command = "npm install && npm run build"
  
  # The publish directory is now relative to the 'base' directory.
  # So, 'build' points to 'frontend/build'.
  publish = "build"

# This section tells Netlify where to find the serverless functions.
# The path is relative to the root of the project.
[functions]
  directory = "backend/functions"