# netlify.toml

# Build settings for the frontend
[build]
  # Set the base directory to the frontend folder
  base = "frontend"
  # The build command will now run from inside the 'frontend' directory
  command = "npm install && npm run build"
  # The publish directory is relative to the 'base' directory
  publish = "build"

# Serverless Functions settings
[functions]
  # The functions directory is relative to the project root
  directory = "backend/functions"
  # This is the key: it copies these files into the functions' deployment package so they can be found
  included_files = ["backend/database.sqlite", "backend/data.js"]
