# netlify.toml
# This file correctly configures the build for a monorepo structure.

# Main build settings, run from the project's root directory.
[build]
  # This command uses the scripts in your root package.json to install
  # all dependencies and then build the frontend application.
  command = "npm install && npm run build"

  # The directory containing your built frontend, relative to the root.
  publish = "frontend/build"

# Serverless Functions settings
[functions]
  # The directory containing your serverless functions, relative to the root.
  directory = "backend/functions"

  # CRITICAL: This copies your data and database files into the deployment
  # package so your live server function can access them.
  included_files = ["backend/data.js", "backend/database.sqlite"]
